import Header from "./components/Header/Header";
import './globals.css';
import { Jost } from 'next/font/google';

export const metadata = {
  title: {
    default: "Designo",
    template: "%s | Designo"
  },
  description: 'Generated by create next app',
  
}

const jost = Jost({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
