export {default as Facebook} from "./Facebook.svg"
export {default as Instagram} from "./Instagram.svg"
export {default as Twitter} from "./Twitter.svg"
export {default as Youtube} from "./Youtube.svg"
export {default as Pinterest} from "./Pinterest.svg"
export {default as Error} from "./icon-error.svg"